<<<<<<< HEAD
[build]
command = 'npm run build'
functions = 'functions'
publish = 'build'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
=======
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
>>>>>>> main
